export const ADD_TO_CART = "ADD_TO_CART";

export const INCREASE_COUNT = "INCREASE_COUNT";

export const DECREASE_COUNT = "DECREASE_COUNT";

export const DELETE_CART_ITEM = "DELETE_CART_ITEM";

export const RESET_CART = "RESET_CART";

export const ADD_SHIPPING_ADDRESS = "ADD_SHIPPING_ADDRESS";
