export const GET_SLIDER_IMAGES_START = "GET_SLIDER_IMAGES_START";
export const GET_SLIDER_IMAGES_SUCCESS = "GET_SLIDER_IMAGES_SUCCESS";
export const GET_SLIDER_IMAGES_FAILED = "GET_SLIDER_IMAGES_FAILED";

export const GET_SEARCH_RESULTS_START = "GET_SEARCH_RESULTS_START";
export const GET_SEARCH_RESULTS_SUCCESS = "GET_SEARCH_RESULTS_SUCCESS";
export const GET_SEARCH_RESULTS_FAILED = "GET_SEARCH_RESULTS_FAILED";

export const GET_FEATURED_PRODUCTS_START = "GET_FEATURED_PRODUCTS_START";
export const GET_FEATURED_PRODUCTS_SUCCESS = "GET_FEATURED_PRODUCTS_SUCCESS";
export const GET_FEATURED_PRODUCTS_FAILED = "GET_FEATURED_PRODUCTS_FAILED";

export const GET_PRODUCT_BY_ID_START = "GET_PRODUCT_BY_ID_START";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAILED = "GET_PRODUCT_BY_ID_FAILED";
