export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

export const USER_GET_PROFILE_START = "USER_GET_PROFILE_START";
export const USER_GET_PROFILE_SUCCESS = "USER_GET_PROFILE_SUCCESS";
export const USER_GET_PROFILE_FAILED = "USER_GET_PROFILE_FAILED";

export const USER_UPDATE_PROFILE_START = "USER_UPDATE_PROFILE_START";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAILED = "USER_UPDATE_PROFILE_FAILED";

export const ADD_REVIEW_START = "ADD_REVIEW_START";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAILED = "ADD_REVIEW_FAILED";
export const ADD_REVIEW_RESET = "ADD_REVIEW_RESET";

export const ADD_REVIEW_TO_PRODUCT = "ADD_REVIEW_TO_PRODUCT";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
